// <auto-generated />
using System;
using EnvironmentCrime_4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnvironmentCrime_4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181012170003_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnvironmentCrime_4.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentId");

                    b.Property<string>("EmployeeName")
                        .IsRequired();

                    b.Property<string>("RoleTitle");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Errand", b =>
                {
                    b.Property<int>("ErrandID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfObservation");

                    b.Property<string>("DepartmentId");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("InformerName")
                        .IsRequired();

                    b.Property<string>("InformerPhone")
                        .IsRequired();

                    b.Property<string>("InvestigatorAction");

                    b.Property<string>("InvestigatorInfo");

                    b.Property<string>("Observation");

                    b.Property<string>("Place")
                        .IsRequired();

                    b.Property<string>("RefNumber");

                    b.Property<string>("StatusId");

                    b.Property<string>("TypeOfCrime")
                        .IsRequired();

                    b.HasKey("ErrandID");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Errands");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.ErrandStatus", b =>
                {
                    b.Property<string>("StatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StatusName");

                    b.HasKey("StatusId");

                    b.ToTable("ErrandStatuses");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ErrandId");

                    b.Property<string>("PictureName");

                    b.HasKey("PictureId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ErrandId");

                    b.Property<string>("SampleName");

                    b.HasKey("SampleId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentValue");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Employee", b =>
                {
                    b.HasOne("EnvironmentCrime_4.Models.Department", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("EnvironmentCrime_4.Models.Errand", b =>
                {
                    b.HasOne("EnvironmentCrime_4.Models.Department", "Department")
                        .WithMany("Errand")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("EnvironmentCrime_4.Models.Employee", "Employee")
                        .WithMany("Errand")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("EnvironmentCrime_4.Models.ErrandStatus", "ErrandStatus")
                        .WithMany("Errands")
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
